Import all the "tor mode" script fixes from Mike Moses Barnard

diff --git a/core-files/usr/local/share/trident/scripts/reset-firewall b/core-files/usr/local/share/trident/scripts/reset-firewall
--- a/core-files/usr/local/share/trident/scripts/reset-firewall
+++ b/core-files/usr/local/share/trident/scripts/reset-firewall
@@ -2,29 +2,68 @@
 # Copyright (c) 2015 Kris Moore (iXsystems / PC-BSD)
 # License: BSD
 
-#Turn off the special config options for the firewall and socat
-sysrc -f /etc/rc.conf -x firewall_script
-sysrc -f /etc/rc.conf -x firewall_coscripts
-sysrc -f /etc/rc.conf -x socat_flags
+## System variables. DO NOT CHANGE
+LOGFILE="/var/log/trident-tor.log"
 
-# If reverting from TOR mode, lets do some cleanup
-if [ -e "/etc/resolv.conf.preTor" ]; then
-  mv /etc/resolv.conf.preTor /etc/resolv.conf
+## Set up our logging
+## Redirect Output to a logfile and screen
+exec 3>&1                         # create pipe (copy of stdout)
+exec 1>$LOGFILE                   # direct stdout to file
+#exec 2>&1                         # uncomment if you want stderr too
 
-  # Stop TOR / SOCAT services
-  service tor stop
-  service socat stop
-
-  # Cleanup rc.conf
-  sysrc -f /etc/rc.conf -x tor_enable
-  sysrc -f /etc/rc.conf -x socat_enable
+## Only privileged user can run this.
+if [ ! `id -u` == "0" ]; then
+  echo "Permission Denied: You need to run this command as root or as a privileged user!"
+  exit 1
+else
+  ## Stop Tor service
+  service tor status
+  if [ $? -eq 3 ]; then
+    echo " "
+    echo "Service Tor has already been stopped or did not start"
+  else
+    service tor stop
+  fi
+  
+  ## Stop socat service
+  service socat status
+  if [ $? -eq 3 ]; then
+    echo " "
+    echo "Service socat has already been stopped or did not start"
+  else
+    service socat stop
+  fi
+  
+  ## Turn off the special config options for the firewall and socat
+  sysrc -f /etc/rc.conf -x firewall_script
+  #sysrc -f /etc/rc.conf -x firewall_coscripts
   sysrc -f /etc/rc.conf -x socat_flags
-fi
+  sysrc -f /etc/rc.conf -x tor_conf
+  sysrc -f /etc/rc.conf -x tor_pidfile
+  sysrc -f /etc/rc.conf -x tor_datadir
+  
+  ## Return dhclient.conf settings to what it was before
+  if [ -e "/etc/dhclient.conf.preTor" ]; then
+    mv /etc/dhclient.conf.preTor /etc/dhclient.conf
+  fi
 
-# If reverting from TOR mode, put back the dhclient config
-if [ -e "/etc/dhclient.conf.preTor" ]; then
-  mv /etc/dhclient.conf.preTor /etc/dhclient.conf
+  ## Return DNS settings to what it was before
+  if [ -e "/etc/resolv.conf.preTor" ]; then
+    mv /etc/resolv.conf.preTor /etc/resolv.conf
+  fi
+  
+  ## Return sysctl.conf file to what it was before.
+  if [ `sysctl -n net.inet.ip.random_id` == "1" ]; then
+    sysctl net.inet.ip.random_id=0
+    sed -i ".postTor" -e "/## Inserted by enable-tor-mode. DO NOT REMOVE/d" -e "/net.inet.ip.random_id=1/d" /etc/sysctl.conf
+    if [ ! $? -eq 0 ]; then
+      echo "Failed to remove Tor sysctl.conf setting. Edit this file manually and remove the entries '##Inserted by enable-tor-mode. DO NOT REMOVE' and 'net.inet.ip.random_id=1'."
+    fi
+    rm -f /etc/sysctl.conf.preTor /etc/sysctl.conf.postTor
+  fi
+  
+  ## Let's restart the firewall
+  service ipfw restart
+  
+  exit 0
 fi
-
-# Start IPFW now
-service ipfw restart
diff --git a/core-files/usr/local/share/trident/scripts/reset-firewall-tor b/core-files/usr/local/share/trident/scripts/reset-firewall-tor
--- a/core-files/usr/local/share/trident/scripts/reset-firewall-tor
+++ b/core-files/usr/local/share/trident/scripts/reset-firewall-tor
@@ -1,56 +1,138 @@
 #!/bin/sh
+#
 # Script to setup IPFW to for TOR forwarding
 # Copyright (c) 2015 Kris Moore (iXsystems / PC-BSD)
 # License: BSD
 
-rules="/usr/local/etc/trident/ipfw.tor.rules"
-torrc="/usr/local/etc/trident/torrc"
+## System variables. DO NOT CHANGE
 
-if [ ! -e "$rules" ] ; then
-  echo "ERROR: Could not find firewall rules for TOR!!"
+RULES="/etc/ipfw-profiles/tor.rules"
+TORRC="/usr/local/etc/trident/torrc"
+LOGFILE="/var/log/trident-tor.log"
+
+## Set up our logging
+## Redirect Output to a logfile and screen
+exec 3>&1                         # create pipe (copy of stdout)
+exec 1>$LOGFILE                   # direct stdout to file
+#exec 2>&1                         # uncomment if you want stderr too
+
+
+
+## Only privileged user can run this.
+if [ ! `id -u` == "0" ]; then
+  echo "Permission Denied: You need to run this command as root or as a privileged user!"
   exit 1
-fi
-
-# Init the TOR database and such
-if [ -d /var/db/tor ]; then
-  rm -r /var/db/tor
-fi
-if [ -d /var/run/tor ]; then
-  rm -r /var/run/tor
-fi
-mkdir -p /var/db/tor/data /var/run/tor
-touch /var/log/tor
-chown -R _tor:_tor /var/db/tor /var/log/tor /var/run/tor
-chmod -R 700 /var/db/tor
-
-# Prevent sequential IP ids
-sysctl net.inet.ip.random_id=1
-if [ 1 -ne `sysctl -n net.inet.ip.random_id`] ; then
-  sysctl net.inet.ip.random_id=1
-  sysrc -q -f /etc/sysctl.conf net.inet.ip.random_id=1
-fi
-
-#Setup the config flacs for the respective services
-sysrc -f /etc/rc.conf firewall_script="${rules}"
-sysrc -f /etc/rc.conf firewall_coscripts="tor socat"
-sysrc -f /etc/rc.conf socat_flags="UDP4-RECVFROM:53,fork UDP4-SENDTO:localhost:9530"
-
-# Now setup DNS resolving
-if [ ! -e "/etc/resolv.conf.preTor" ] ; then
-  touch /etc/resolv.conf
-  cp /etc/resolv.conf /etc/resolv.conf.preTor
-fi
-echo "nameserver 127.0.0.1" > /etc/resolv.conf
-
-# Massage the dhclient.conf
-if [ -e "/etc/dhclient.conf" ] ; then
-  if [ ! -e "/etc/dhclient.conf.preTor" ] ; then
-    cp /etc/dhclient.conf /etc/dhclient.conf.preTor
+else
+  ## Some sanity checks.
+  ## Check if the ipfw rules file is present. If not, exit.
+  if [ ! -e "$RULES" ] ; then
+    echo "ERROR: Could not find TOR IPFW firewall rules ($RULES)!!"
+    exit 1
   fi
-  cat /etc/dhclient.conf | grep -v "supersede domain-name-servers" > /etc/dhclient.conf.new
-  mv /etc/dhclient.conf.new /etc/dhclient.conf
-fi
-echo "supersede domain-name-servers 127.0.0.1;" >> /etc/dhclient.conf
 
-# Now lets restart the firewall
-service ipfw restart
+  ## Check if TOR configuration file exists. If not, exit.
+  if [ ! -e "$TORRC" ] ; then
+    echo "ERROR: Could not find TOR configuration file ($TORRC)!!"
+    exit 1
+  fi
+
+  ## If we haven't run enable-tor-more before, init necessary directories
+  if [ ! -e /tmp/.trident-tor.done ]; then
+  
+    ## Initiate TOR Database, logfile and other needed directories
+    # Init the TOR database
+    if [ -d /var/db/tor ]; then
+      rm -r /var/db/tor
+    fi
+    
+    # Init TOR run directory
+    if [ -d /var/run/tor ]; then
+      rm -r /var/run/tor
+    fi
+    
+    # Init TOR log directory
+    if [ -d /var/log/tor ]; then
+      rm -r /var/log/tor
+    fi
+    
+    # Init Trident-TOR log file
+    if [ ! -e "/var/log/trident-tor.log" ]; then
+      touch /var/log/trident-tor.log
+    fi
+
+    # Create the directories and set necessary permissions
+    mkdir -p /var/db/tor/data /var/run/tor /var/log/tor
+    chown -R _tor:_tor /var/db/tor /var/log/tor /var/run/tor
+    chmod -R 700 /var/db/tor
+    
+    # Set flag for init directories
+    touch /tmp/.trident-tor.done
+    chown -R _tor:_tor /tmp/.trident-tor.done
+    chmod -R 400 /tmp/.trident-tor.done
+  fi
+  
+  ## Prevent sequential IP ids
+  if [ `sysctl -n net.inet.ip.random_id` == "0" ]; then
+    sysctl net.inet.ip.random_id=1
+    # Make it persistent between reboots. CAUTION: This is not a safe method to edit the sysctl.conf file
+    # If you make any changes to your sysctl.conf file after this command, they will be lost when you 
+    # run disable-tor-more. Find a better way to add this to sysctl.conf
+    cp /etc/sysctl.conf /etc/sysctl.conf.preTor
+  fi
+  echo "## Inserted by enable-tor-mode. DO NOT REMOVE" >> /etc/sysctl.conf
+  echo "net.inet.ip.random_id=1" >> /etc/sysctl.conf
+
+  ## Now setup DNS resolving
+  if [ ! -e "/etc/resolv.conf.preTor" ]; then
+    touch /etc/resolv.conf
+    cp /etc/resolv.conf /etc/resolv.conf.preTor
+  fi
+  echo "nameserver 127.0.0.1" > /etc/resolv.conf
+
+  ## Massage the dhclient.conf
+  if [ -e "/etc/dhclient.conf" ]; then
+    if [ ! -e "/etc/dhclient.conf.preTor" ]; then
+      cp /etc/dhclient.conf /etc/dhclient.conf.preTor
+    fi
+    cat /etc/dhclient.conf | grep -v "supersede domain-name-servers" > /etc/dhclient.conf.new
+    mv /etc/dhclient.conf.new /etc/dhclient.conf
+  fi
+  echo "supersede domain-name-servers 127.0.0.1;" >> /etc/dhclient.conf
+  
+  ## Setup the config flacs for the respective services
+  sysrc -f /etc/rc.conf firewall_script="${RULES}"
+  #sysrc -f /etc/rc.conf firewall_coscripts="/etc/ipfw-profiles/tor.rules"
+  sysrc -f /etc/rc.conf socat_flags="UDP4-RECVFROM:53,fork UDP4-SENDTO:localhost:9530"
+  sysrc -f /etc/rc.conf tor_conf="${TORRC}"
+  sysrc -f /etc/rc.conf tor_pidfile="/var/run/tor/tor.pid"
+  sysrc -f /etc/rc.conf tor_datadir="/var/db/tor"
+
+  ## Let's restart the firewall
+  service ipfw restart
+  service ipfw status
+  if [ $? -eq 3 ]; then
+    echo "IPFW Failed to restart. Rolling back..."
+    /usr/local/bin/disable-tor-mode
+    exit 1
+  fi
+  
+  ## Let's start socat
+  service socat start
+  service socat status
+  if [ $? -eq 3 ]; then
+    echo "socat Failed to restart. Rolling back..."
+    /usr/local/bin/disable-tor-mode
+    exit 1
+  fi
+  
+  ## Let's start tor with the trident-tor config file
+  service tor start
+  service tor status
+   if [ $? -eq 3 ]; then
+    echo "TOR Failed to restart. Rolling back..."
+    /usr/local/bin/disable-tor-mode
+    exit 1
+  fi
+ 
+  exit 0
+fi
